

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using System.Resources;

// Compute version values


//Fork release: 2

// General Information
[assembly: AssemblyTitle("mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Next Generation Connection Manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("Profi-KOM Ltd.")]
[assembly: AssemblyProduct("mRemoteNG Connection Manager")]
[assembly: AssemblyCopyright("(c) 2026 mRemoteNG")]
[assembly: AssemblyTrademark("Profi-KOM LTd.")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("1.78.2.2")]
[assembly: AssemblyFileVersion("1.78.2.2")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.78.2-yll.2 x64")]
